version: '3'

services:
  mongo:
    image: mongo:6.0.6
    environment:
      - AUTH=no
      # ホストマシンから繋ぎたいとき
      - MONGO_REPLICA_HOST=localhost
      # 他のコンテナから繋ぎたいとき
      # - MONGO_REPLICA_HOST=host.docker.internal
    command: [--replSet, rs0, --noauth, --bind_ip_all]
    ports:
      - 27017:27017
    healthcheck:
      test: mongosh mongo-init.js
      interval: 10s
      start_period: 30s
    volumes:
      # 他のコンテナから繋ぎたいとき
      - ./docker/mongo/data:/data/db
      - ./docker/scripts/mongo-init.js:/mongo-init.js
    restart: always
