import { redirect } from 'next/navigation';
import { accessToken } from '../_helpers/auth';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default async function Layout(props: { children: React.ReactNode }) {
  const { children } = props;
  if (!accessToken()) {
    redirect('/signin');
  }
  return <>{children}</>;
}
