import ThemeRegistry from './ThemeRegistry';
import Header from './Header';
import GlobalContextProvider from './contexts/GlobalContextProvider';
import { UserContextProvider } from './contexts/UserContext';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
          <GlobalContextProvider>
            <Header />
            {children}
          </GlobalContextProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
