import ThemeRegistry from './ThemeRegistry';
import { AppBar, Typography, Grid } from '@mui/material';
import { UserContextProvider } from './contexts/UserContext';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
          <AppBar position="static">
            <Grid container>
              <Grid item xs={2} />
              <Grid item xs={8}>
                <Typography variant="h1" fontWeight="bold" fontSize={'4rem'}>
                  ChatApp
                </Typography>
              </Grid>
              <Grid item xs={2} />
            </Grid>
          </AppBar>
          <UserContextProvider>{children}</UserContextProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
