import ThemeRegistry from './_theme/ThemeRegistry';
import UserIcon from './userIcon';
import GlobalContextProvider from './_contexts/GlobalContextProvider';
import { AppBar, Box, Typography } from '@mui/material';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;

  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <GlobalContextProvider>
            <AppBar position="static">
              <Box
                display="flex"
                flexDirection="row"
                alignItems="center"
                justifyContent="space-between"
                padding="10px 50px"
              >
                <Typography
                  variant="h1"
                  fontWeight="bold"
                  fontSize={'3rem'}
                  align="center"
                >
                  ChatApp
                </Typography>
                <Box display="flex" flexDirection="row" alignItems="center">
                  <UserIcon />
                </Box>
              </Box>
            </AppBar>
            {children}
          </GlobalContextProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
